name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Reassemble and Unzip Wetterdaten
        run: |
          if [ -f website_daten.zip.part_aa ]; then
            echo "Split-Dateien gefunden. Setze ZIP-Datei zusammen..."
            cat website_daten.zip.part_* > website_daten.zip
            rm website_daten.zip.part_*
          fi
          unzip -o website_daten.zip -d .
          rm website_daten.zip

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
